# Generated by Django 2.0.3 on 2018-03-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0002_auto_20180323_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smarthouseuser',
            old_name='apellidos',
            new_name='Apellidos',
        ),
        migrations.RenameField(
            model_name='smarthouseuser',
            old_name='id_social',
            new_name='Id_social',
        ),
        migrations.RenameField(
            model_name='smarthouseuser',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='smarthouseuser',
            old_name='root',
            new_name='Root',
        ),
    ]
