# Generated by Django 2.0.3 on 2018-03-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0003_auto_20180323_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartHouseUser',
            new_name='Usuario',
        ),
    ]
