# Generated by Django 2.0.4 on 2018-04-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Dispositivos')),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RolesUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activado', models.BooleanField(default=False)),
                ('rolId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RutinasUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activada', models.BooleanField(default=False)),
                ('rutinaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Rutinas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='rutinasusuarios',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Usuarios'),
        ),
        migrations.AddField(
            model_name='rolesusuarios',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Usuarios'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Usuarios'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='lugarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Lugares'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='tipoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.TipoDispositivo'),
        ),
    ]
