# Generated by Django 2.0.3 on 2018-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0006_auto_20180426_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.CharField(default='usuario@email.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.CharField(default='https://enlace a foto', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idGoogle',
            field=models.CharField(default='12312125163213412', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
