# Generated by Django 2.0.3 on 2018-06-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0008_auto_20180610_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='grupoPermisos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Roles'),
        ),
    ]
