# Generated by Django 2.0.3 on 2018-06-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0010_auto_20180610_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesusuarios',
            name='activado',
            field=models.BooleanField(),
        ),
    ]
