# Generated by Django 2.0.3 on 2018-06-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0011_auto_20180610_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesusuarios',
            name='activado',
            field=models.IntegerField(default=0),
        ),
    ]
