# Generated by Django 2.0.3 on 2018-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0012_auto_20180610_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='activado',
            field=models.IntegerField(default=0),
        ),
    ]
