# Generated by Django 2.0.3 on 2018-06-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0013_auto_20180610_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calefaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Dispositivos')),
            ],
        ),
    ]
