# Generated by Django 2.0.3 on 2018-06-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0014_calefaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calefaccion',
            name='dispositivoId',
        ),
        migrations.AddField(
            model_name='rutinas',
            name='dispositivoId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Dispositivos'),
        ),
        migrations.DeleteModel(
            name='Calefaccion',
        ),
    ]
