# Generated by Django 2.0.3 on 2018-06-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0015_auto_20180611_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinas',
            name='dispositivoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Dispositivos'),
        ),
    ]
