# Generated by Django 2.0.3 on 2018-06-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHouse', '0016_auto_20180611_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('grupoId', models.CharField(max_length=200)),
                ('beaconId', models.CharField(max_length=200)),
                ('rango', models.IntegerField()),
                ('lugarId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHouse.Lugares')),
            ],
        ),
    ]
